# custom.***ã¨è¨€ã†åå‰ã§èªè­˜ã—ã¦ãã‚Œã‚‹ã€‚
[custom.cdk]
# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã«è¡¨ç¤ºã•ã‚Œã‚‹å†…å®¹ã€‚å®Ÿè¡ŒçµæœãŒ$outputå¤‰æ•°ã«æ ¼ç´ã•ã‚Œã‚‹ã€‚
command = "echo $CDK_VERSION"
# cdkã®ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’è¡¨ç¤ºã™ã‚‹æ¡ä»¶ã€‚
# å®Ÿè¡Œã™ã‚‹ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã«`cdk.json`ãŒã‚ã‚‹å ´åˆ
when = """ test -e cdk.json """
# ã‚·ãƒ³ãƒœãƒ«
symbol = "cdk: "
# è¡¨ç¤ºã®ãƒ•ã‚©ãƒ¼ãƒãƒƒãƒˆ
format = "[$symbol$output]($style)"

# ä¸€è¡Œæ”¹è¡Œã™ã‚‹ã‹(ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆï¼štrue)
add_newline = false

# è¡¨ç¤ºã•ã‚Œã‚‹é …ç›®ã®é †åºã®è¨­å®š(åŸºæœ¬ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã§è‰¯ã„)
prompt_order = [
    "username",
    "directory",
    "line_break", #æ”¹è¡Œã‚’å…¥ã‚ŒãŸã„ä½ç½®ã«è¿½åŠ 
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "character"
]

# ãƒ†ã‚­ã‚¹ãƒˆãŒå…¥åŠ›ã•ã‚Œã‚‹å ´æ‰€ã‚’ç¤ºã™æ–‡å­—ã®è¨­å®š
[character]
symbol = "$" # æ–‡å­—ã‚’å¤‰æ›´(ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã¯ > )

# æ”¹è¡Œè‡ªä½“ã®è¨­å®š
[line_break]
disabled = true # éè¡¨ç¤ºã«è¨­å®š

# æ™‚é–“ã®è¨­å®š
[time]
disabled = true # éè¡¨ç¤ºã«è¨­å®šã™ã‚‹ã¨ã€å¿…ãšä¸€è¡Œã«ãªã‚‹

# gitã®ãƒ–ãƒ©ãƒ³ãƒã®è¡¨ç¤º
[git_branch]
symbol = "ğŸŒ± " #ã‚¢ã‚¤ã‚³ãƒ³çµµæ–‡å­—ã‚’å¤‰æ›´

# gitã®statusã®è¡¨ç¤º
[git_status]
modified = "+" #ãƒ•ã‚¡ã‚¤ãƒ«ã®å¤‰æ›´ãŒã‚ã‚‹å ´åˆã®è¡¨ç¤ºã‚’å¤‰æ›´
prefix = "("
suffix = ") "
